Remove install folder, move docker in-repo, simplify install

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -4,7 +4,7 @@ usage () {
   echo "Usage: ${0} COMMAND CONFIG [--skip-prereqs] [--docker-args STRING]"
   echo "Commands:"
   echo "    env:       Create a Python virtual environment"
-  echo "    install:   Run the installation script"
+  echo "    install:   Installs developer environment"
   echo "    test:      Run tests with coverage"
   echo "    run:       Runs Django webserver"
   echo "    start:     Runs the Django webserver"
@@ -26,7 +26,87 @@ run_env() {
 }
 
 run_install() {
-    ./install/install.sh dev
+    echo "Installing the Krypted Platform developer environment"
+    if [ ! -d "./app" ]; then
+        echo "Please run in the root project directory"
+        exit 1
+    fi
+
+    command=$1
+
+    if [ -n "$command" ]; then
+        case "$command" in 
+            dev)
+            DEV_MODE=true
+            ;;
+            *)
+            usage
+            exit 1
+            ;;
+        esac
+    fi
+
+    # Install python requirements
+    echo "Installing Python Requirements"
+    pip3 install -r requirements.txt
+    if [ $? -ne 0 ]; then 
+        echo "Failed to install Python requirements"
+        exit 1
+    fi 
+    if [ $DEV_MODE ]; then
+        echo "Installing Python Development Requirements"
+        pip3 install coverage python-coveralls sphinx-markdown-tables django-extensions ipython notebook
+        if [ $? -ne 0 ]; then 
+            echo "Failed to install Python Development requirements"
+            exit 1
+        fi 
+    fi
+
+    # Install Developer Settings
+    cp ./install/settings_developer.py.example ./app/app/settings.py
+
+    # Set up the Django project
+    echo "Setting up the Django Project"
+    echo "Creating migrations for project"
+    python3 ./app/manage.py makemigrations
+    if [ $? -ne 0 ]; then 
+        echo "Failed to set up the Django project"
+        exit 1
+    fi 
+    echo "Creating migrations for specific subprojects"
+    python3 ./app/manage.py makemigrations accounts
+    if [ $? -ne 0 ]; then 
+        echo "Failed to set up the Django project"
+        exit 1
+    fi 
+    echo "Creating database for project"
+    python3 ./app/manage.py migrate 
+    if [ $? -ne 0 ]; then 
+        echo "Failed to set up the Django project"
+        exit 1
+    fi 
+
+    # Create STATIC directory
+    mkdir -p ./app/app/static
+    mkdir -p ./app/accounts/static
+
+    # Install AdminLTE UI
+    echo "Installing AdminLTE in app/static/adminlte/"
+    wget https://github.com/KryptedGaming/krypted/releases/download/v4.0.0/AdminLTE-2.4.15.tar.gz
+    tar -xvf AdminLTE-2.4.15.tar.gz -C ./app/app/static/
+    rm AdminLTE-2.4.15.tar.gz*
+
+    # Install AccountStylingV2
+    echo "Installing Accounts Styling in app/static/accounts"
+    wget https://github.com/KryptedGaming/krypted/releases/download/v4.0.0/Accounts_v12.tar.gz
+    tar -xvf Accounts_v12.tar.gz -C ./app/accounts/static/
+    rm Accounts_v12.tar.gz*
+
+    # Collect static
+    python3 ./app/manage.py collectstatic
+
+    # Create cache table
+    python3 ./app/manage.py createcachetable
 }
 
 run_test() {
@@ -42,7 +122,7 @@ run_server() {
 
 run_shell() {
     cd ./app/
-    python3 manage.py shell
+    python3 manage.py shell_plus
 }
 
 run_migrate() {
